name: Benchmarks

on:
  push:
    branches: [ "bench_test" ]

permissions:
  id-token: write
  contents: write

jobs:
  integration:
    name: Benchmarks
    uses: ./.github/workflows/bench.yml
    with:
      ref: ${{ github.event.after }}
